apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ExternalSecret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: secret
    creationPolicy: Owner
  data:
    - secretKey: KEY1
      remoteRef:
        key: dd-staging-backend-redis
        property: redis_addresses1
