name: Release

on:
  push:
    # tags:
    #   - "v*.*.*"
    branches:
      - github-build-*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21"
      - run: GOOS=linux GOARCH=amd64 go build -o main .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main
